# project introduction 
This project explores historical data collected by Florence Nightingale during the Crimean War. Nightingale was one of the first people to use statistical graphics to communicate important health insights.

The dataset records the average army size and the number of deaths caused by disease, wounds, and other factors for each month. Her analysis revealed that far more soldiers died from preventable diseases than from battle injuries.

In this project, Python will be used to analyze the dataset and recreate Nightingale’s famous coxcomb (polar area) chart. The visualization helps illustrate the distribution of deaths by cause and demonstrates how data visualization can be used to communicate powerful insights and support improvements in public health.

In [1]:
# import libraries
import numpy as np
import pandas as pd
import janitor
from lets_plot import *
LetsPlot.setup_html()

In [2]:
# load your dataset
data_set1 = pd.read_excel("C:/Users/user/Downloads/mini project/mini project/Nightingale/raw_night_1854_1855.xlsx")

In [3]:
# check the data head
data_set1.head()

      Month  Avg Army Size  Disease Deaths  Wounds  Other Causes
0  Apr 1854           8571               1       0             5
1  May 1854          23333              12       0             9
2  Jun 1854          28333              11       0             6
3  Jul 1854          28722             359       0            23
4  Aug 1854          30246             828       1            30

In [4]:
# check data1 info
data_set1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Month           12 non-null     object
 1   Avg Army Size   12 non-null     int64
 2   Disease Deaths  12 non-null     int64
 3   Wounds          12 non-null     int64
 4   Other Causes    12 non-null     int64
dtypes: int64(4), object(1)
memory usage: 612.0+ bytes

In [5]:
data_set1.columns

Index(['Month', 'Avg Army Size', 'Disease Deaths', 'Wounds', 'Other Causes'], dtype='object')

In [6]:
data_set1

       Month  Avg Army Size  Disease Deaths  Wounds  Other Causes
0   Apr 1854           8571               1       0             5
1   May 1854          23333              12       0             9
2   Jun 1854          28333              11       0             6
3   Jul 1854          28722             359       0            23
4   Aug 1854          30246             828       1            30
5   Sep 1854          30290             788      81            70
6   Oct 1854          30643             503     132           128
7   Nov 1854          27543             844     287           106
8   Dec 1854          32393            1725     114           131
9   Jan 1855          32393            2761      83           324
10  Feb 1855          30460            2120      42           361
11  Mar 1855          32393            1207      32           172

In [7]:
data1 = data_set1["Month"].str.split(" ", expand = True).rename(columns = {0: "month_2",
                                                       1: "year"})

In [8]:
nightingale_1854 = pd.concat([data_set1, data1], axis =1 )
nightingale_1854

,Month,Avg Army Size,Disease Deaths,Wounds,Other Causes,month_2,year
0,Apr 1854,8571,1,0,5,Apr,1854
1,May 1854,23333,12,0,9,May,1854
2,Jun 1854,28333,11,0,6,Jun,1854
3,Jul 1854,28722,359,0,23,Jul,1854
4,Aug 1854,30246,828,1,30,Aug,1854
5,Sep 1854,30290,788,81,70,Sep,1854
6,Oct 1854,30643,503,132,128,Oct,1854
7,Nov 1854,27543,844,287,106,Nov,1854
8,Dec 1854,32393,1725,114,131,Dec,1854
9,Jan 1855,32393,2761,83,324,Jan,1855
10,Feb 1855,30460,2120,42,361,Feb,1855
11,Mar 1855,32393,1207,32,172,Mar,1855

 The dataset was originally in a wide format where each cause of death (disease, wounds, and other) existed in separate columns. To prepare the data for visualization with plotnine, the dataset was reshaped into a long format using the pivot_ longer() function. This structure creates a single column for the cause of death and another for the number of deaths, making it easier to map variables such as month, deaths, and cause to the chart aesthetics when creating the coxcomb visualization.

In [9]:
nightingale_1 = nightingale_1854.pivot_longer(index = ["Month", "Avg Army Size", "month_2",	"year"],
                names_to = "disease",
                values_to = "count")

nightingale_1.head()

      Month  Avg Army Size month_2  year         disease  count
0  Apr 1854           8571     Apr  1854  Disease Deaths      1
1  May 1854          23333     May  1854  Disease Deaths     12
2  Jun 1854          28333     Jun  1854  Disease Deaths     11
3  Jul 1854          28722     Jul  1854  Disease Deaths    359
4  Aug 1854          30246     Aug  1854  Disease Deaths    828

In [10]:
nightingale_1["sqrt_count"] = np.sqrt(nightingale_1["count"])

nightingale_1.head()

      Month  Avg Army Size month_2  year         disease  count  sqrt_count
0  Apr 1854           8571     Apr  1854  Disease Deaths      1    1.000000
1  May 1854          23333     May  1854  Disease Deaths     12    3.464102
2  Jun 1854          28333     Jun  1854  Disease Deaths     11    3.316625
3  Jul 1854          28722     Jul  1854  Disease Deaths    359   18.947295
4  Aug 1854          30246     Aug  1854  Disease Deaths    828   28.774989

In [11]:
nightingale_1["month_2"] = pd.Categorical(nightingale_1["month_2"],
              categories = ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb",  "Mar", "Apr", "May", "Jun"],
              ordered = True)

In [12]:
nightingale_1["disease"] = pd.Categorical(nightingale_1["disease"],
              categories = ["Wounds", "Other Causes", "Disease Deaths"],
              ordered = True)

In [32]:
p1 = (ggplot(nightingale_1, aes("month_2", "sqrt_count", fill = "disease"))
+ geom_bar(stat='identity', alpha = 0.6)
+ scale_fill_manual(values = ["#fb9a99", "grey30", "skyblue"]) 
#+ coord_equal(ratio = 1) 
+ coord_polar()
+ labs(fill = "Disease",
      subtitle = ("APIRL 1854 TO MARCH 1855")) 
+ theme(axis_title_y = element_blank(),
        axis_title_x = element_blank(),
        axis_text_y = element_blank(),
        axis_ticks = element_blank(),
        plot_subtitle = element_text(hjust = 0.5),
        panel_grid = element_blank(),
        panel_border = element_blank(),
         legend_position = "bottom")
+  ggsize(900, 550))

p1

In [14]:
# load your dataset
data_set2 = pd.read_excel("C:/Users/user/Downloads/mini project/mini project/Nightingale/raw_night_1855_1856.xlsx")

In [15]:
# check the data head
data_set2.head()

      Month  Avg Army Size  Disease Deaths  Wounds  Other Causes
0  Apr 1855          32393             477      48            57
1  May 1855          35693             508      32            37
2  Jun 1855          40253             802      31            31
3  Jul 1855          35786             382      30            33
4  Aug 1855          51074             483      41            55

In [16]:
# check data2 info
data_set2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Month           12 non-null     object
 1   Avg Army Size   12 non-null     int64
 2   Disease Deaths  12 non-null     int64
 3   Wounds          12 non-null     int64
 4   Other Causes    12 non-null     int64
dtypes: int64(4), object(1)
memory usage: 612.0+ bytes

In [17]:
data_set2.columns

Index(['Month', 'Avg Army Size', 'Disease Deaths', 'Wounds', 'Other Causes'], dtype='object')

In [18]:
data_set2

       Month  Avg Army Size  Disease Deaths  Wounds  Other Causes
0   Apr 1855          32393             477      48            57
1   May 1855          35693             508      32            37
2   Jun 1855          40253             802      31            31
3   Jul 1855          35786             382      30            33
4   Aug 1855          51074             483      41            55
5   Sep 1855          52280             189      47            37
6   Oct 1855          53321             128      36            33
7   Nov 1855          45679             178      19            18
8   Dec 1855          36241              91      15            15
9   Jan 1856          34292              42       2             3
10  Feb 1856          34392              24       0             2
11  Mar 1856          36667              15       0             4

In [19]:
data2 = data_set2["Month"].str.split(" ", expand = True).rename(columns = {0: "month_2",
                                                       1: "year"})

In [20]:
nightingale_1856 = pd.concat([data_set2, data2], axis =1 )
nightingale_1856

,Month,Avg Army Size,Disease Deaths,Wounds,Other Causes,month_2,year
0,Apr 1855,32393,477,48,57,Apr,1855
1,May 1855,35693,508,32,37,May,1855
2,Jun 1855,40253,802,31,31,Jun,1855
3,Jul 1855,35786,382,30,33,Jul,1855
4,Aug 1855,51074,483,41,55,Aug,1855
5,Sep 1855,52280,189,47,37,Sep,1855
6,Oct 1855,53321,128,36,33,Oct,1855
7,Nov 1855,45679,178,19,18,Nov,1855
8,Dec 1855,36241,91,15,15,Dec,1855
9,Jan 1856,34292,42,2,3,Jan,1856
10,Feb 1856,34392,24,0,2,Feb,1856
11,Mar 1856,36667,15,0,4,Mar,1856

The dataset was originally in a wide format where each cause of death (disease, wounds, and other) existed in separate columns. To prepare the data for visualization with plotnine, the dataset was reshaped into a long format using the pivot_ longer() function. This structure creates a single column for the cause of death and another for the number of deaths, making it easier to map variables such as month, deaths, and cause to the chart aesthetics when creating the coxcomb visualization.

In [21]:
nightingale_2 = nightingale_1856.pivot_longer(index = ["Month", "Avg Army Size", "month_2",	"year"],
                names_to = "disease",
                values_to = "count")

nightingale_2.head()

      Month  Avg Army Size month_2  year         disease  count
0  Apr 1855          32393     Apr  1855  Disease Deaths    477
1  May 1855          35693     May  1855  Disease Deaths    508
2  Jun 1855          40253     Jun  1855  Disease Deaths    802
3  Jul 1855          35786     Jul  1855  Disease Deaths    382
4  Aug 1855          51074     Aug  1855  Disease Deaths    483

In [22]:
nightingale_2["sqrt_count"] = np.sqrt(nightingale_2["count"])

nightingale_2.head()

      Month  Avg Army Size month_2  year         disease  count  sqrt_count
0  Apr 1855          32393     Apr  1855  Disease Deaths    477   21.840330
1  May 1855          35693     May  1855  Disease Deaths    508   22.538855
2  Jun 1855          40253     Jun  1855  Disease Deaths    802   28.319605
3  Jul 1855          35786     Jul  1855  Disease Deaths    382   19.544820
4  Aug 1855          51074     Aug  1855  Disease Deaths    483   21.977261

In [23]:
nightingale_2["month_2"] = pd.Categorical(nightingale_2["month_2"],
              categories = ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb",  "Mar", "Apr", "May", "Jun"],
              ordered = True)

In [24]:
nightingale_2["disease"] = pd.Categorical(nightingale_2["disease"],
              categories = ["Wounds", "Other Causes", "Disease Deaths"],
              ordered = True)

In [30]:
p2 = (ggplot(nightingale_2, aes("month_2", "sqrt_count", fill = "disease"))
+ geom_bar(stat='identity', alpha = 0.6)
+ scale_fill_manual(values = ["#fb9a99", "grey30", "skyblue"]) 
#+ coord_equal(ratio = 1) 
+ coord_polar()
+ labs(fill = "Disease",
      subtitle = "APIRL 1855 TO MARCH 1856") 
+ theme(axis_title_y = element_blank(),
        axis_title_x = element_blank(),
        axis_text_y = element_blank(),
        axis_ticks = element_blank(),
        plot_subtitle = element_text(hjust = 0.5),
        panel_grid = element_blank(),
        panel_border = element_blank(),
         legend_position = "bottom")
+  ggsize(900, 550))

p2

In [35]:
gggrid([p2, p1], ncol = 2)

Florence Nightingale’s coxcomb diagram powerfully demonstrates that the majority of deaths during the Crimean War’s first winter were caused by preventable diseases rather than battle wounds. The visualizations reveal a striking contrast: massive blue wedges (preventable diseases) dominate the 1854–1855 period, especially in cold months, while the 1855–1856 period shows a dramatic reduction after sanitary reforms (clean water, ventilation, hygiene). Bar and stacked area charts confirm this pattern in linear form, while the polar area chart makes the seasonal and proportional impact immediately obvious — exactly as Nightingale intended.

The most important insight is that most mortality was avoidable through simple environmental changes, not medical treatment. This supports Nightingale’s legacy in evidence-based public health and hospital reform. The project also highlights the power of thoughtful visualization: by using area (not height) and polar coordinates, Nightingale turned complex statistics into a compelling argument that influenced policy and saved lives.

Future analysis could incorporate troop strength data or compare with other wars to further contextualize the impact.